version: '3.7'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "6970:8096"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /home/ubuntu/Downloads:/media:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "6971:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - qbittorrent_config:/config
      - /home/ubuntu/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - radarr_config:/config
      - /home/ubuntu/Downloads:/downloads
      - /home/ubuntu/Downloads/Movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    depends_on:
      - qbittorrent

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - sonarr_config:/config
      - /home/ubuntu/Downloads:/downloads
      - /home/ubuntu/Downloads/Shows:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    depends_on:
      - qbittorrent

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - prowlarr_config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    depends_on:
      - flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Etc/UTC

volumes:
  jellyfin_config:
  jellyfin_cache:
  qbittorrent_config:
  radarr_config:
  sonarr_config:
  prowlarr_config:
